
// must dervice latest python base image (FROM)
// set WORKDIR as <netid>_PA4
// copy python2.py script into working directory
// copy requirements.txt into working directory
// use RUN command to pip3 install all required libraries from the requirements.txt file
// use CMD instruction to run python script with appropriate CLAs
